server:
  port: 8082
  servlet:
    context-path: /
spring:
  activemq:
    user: admin
    password: admin
    broker-url: tcp://192.168.2.42:61616
    pool:
      enabled: true
      max-connections: 10

queueName: publish.queue
topicName: publish.topic